In [1]:
!wget http://labfile.oss.aliyuncs.com/courses/1081/course-14-student.csv

--2018-09-26 22:06:47--  http://labfile.oss.aliyuncs.com/courses/1081/course-14-student.csv
Resolving labfile.oss.aliyuncs.com (labfile.oss.aliyuncs.com)... 118.178.161.16
Connecting to labfile.oss.aliyuncs.com (labfile.oss.aliyuncs.com)|118.178.161.16|:80... failed: Unknown error.
Retrying.

--2018-09-26 22:07:09--  (try: 2)  http://labfile.oss.aliyuncs.com/courses/1081/course-14-student.csv
Connecting to labfile.oss.aliyuncs.com (labfile.oss.aliyuncs.com)|118.178.161.16|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23076 (23K) [text/csv]
Saving to: 'course-14-student.csv'

     0K .......... .......... ..                              100% 34.7K=0.6s

2018-09-26 22:07:10 (34.7 KB/s) - 'course-14-student.csv' saved [23076/23076]



In [2]:
import pandas as pd

stu_data = pd.read_csv("course-14-student.csv")
stu_data.head(10)

Unnamed: 0  school  sex  address  Pstatus  Pedu  reason  guardian  \
0           0       0    0        0        0     1       2         2   
1           1       0    0        0        1     2       2         0   
2           2       0    0        0        1     2       0         2   
3           3       0    0        0        1     0       1         2   
4           4       0    0        0        1     0       1         0   
5           5       0    1        0        1     0       3         2   
6           6       0    1        0        1     0       1         2   
7           7       0    0        0        0     1       1         2   
8           8       0    1        0        0     0       1         2   
9           9       0    1        0        1     0       1         2   

   traveltime  studytime ...  famrel  freetime  goout  Dalc  Walc  health  \
0           1          1 ...       3         2      3     0     0       2   
1           0          1 ...       4         2      2     0     0       2   
2           0          1 ...       3         2      1     1     2       2   
3           0          2 ...       2         1      1     0     0       4   
4           0          1 ...       3         2      1     0     1       4   
5           0          1 ...       4         3      1     0     1       4   
6           0          1 ...       3         3      3     0     0       2   
7           1          1 ...       3         0      3     0     0       0   
8           0          1 ...       3         1      1     0     0       0   
9           0          1 ...       4         4      0     0     0       4   

   absences  G1  G2  G3  
0         6   2   2   2  
1         4   2   2   2  
2        10   2   2   3  
3         2   3   3   1  
4         4   2   3   3  
5        10   3   1   1  
6         0   1   3   3  
7         6   2   2   2  
8         0   3   1   1  
9         0   1   1   1  

[10 rows x 28 columns]

In [3]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(stu_data.iloc[:,:-1], stu_data["G3"],
                                                    test_size=0.3, random_state=35)
x_test.head(10)

Unnamed: 0  school  sex  address  Pstatus  Pedu  reason  guardian  \
17           17       0    0        0        1     0       3         2   
355         355       1    0        0        1     0       2         0   
311         311       0    0        0        1     2       0         1   
103         103       0    0        0        1     0       1         2   
195         195       0    0        0        1     0       2         0   
86           86       0    0        0        1     0       2         2   
28           28       0    1        0        0     0       1         2   
307         307       0    1        0        1     1       3         1   
116         116       0    1        0        1     1       3         0   
143         143       0    0        0        1     2       2         2   

     traveltime  studytime ...  romantic  famrel  freetime  goout  Dalc  Walc  \
17            2          1 ...         1       4         2      1     0     0   
355           0          1 ...         0       4         2      3     0     0   
311           2          1 ...         0       2         3      0     0     0   
103           1          1 ...         1       3         2      4     0     0   
195           0          1 ...         0       3         2      1     0     0   
86            0          1 ...         1       3         2      3     0     1   
28            0          1 ...         1       4         2      2     0     0   
307           1          0 ...         0       3         2      3     0     0   
116           1          1 ...         1       3         3      2     0     0   
143           0          0 ...         1       2         3      3     2     2   

     health  absences  G1  G2  
17        3         4   2   3  
355       4         0   1   2  
311       1        20   1   3  
103       1        26   2   2  
195       4         0   1   1  
86        1         4   2   2  
28        4         4   1   3  
307       3        29   2   2  
116       1         2   1   3  
143       0         2   1   3  

[10 rows x 27 columns]

In [4]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(criterion='entropy', random_state=34)
dt_model.fit(x_train, y_train)  # 使用训练集训练模型
dt_y_predict = dt_model.predict(x_test)
dt_y_predict

array([2, 0, 3, 2, 1, 2, 2, 2, 3, 3, 0, 2, 1, 3, 3, 2, 3, 0, 1, 2, 1, 2,
       1, 2, 3, 3, 3, 0, 3, 3, 3, 3, 2, 2, 3, 3, 0, 1, 2, 2, 2, 1, 3, 2,
       1, 3, 2, 3, 3, 3, 3, 1, 1, 3, 2, 0, 1, 3, 2, 3, 3, 0, 0, 2, 2, 3,
       3, 3, 2, 1, 0, 3, 2, 2, 3, 2, 1, 3, 0, 2, 3, 1, 3, 3, 0, 3, 3, 1,
       3, 3, 1, 3, 3, 3, 2, 0, 2, 3, 0, 3, 1, 3, 1, 1, 3, 3, 3, 3, 3, 3,
       2, 1, 1, 1, 3, 0, 3, 3, 3], dtype=int64)

In [5]:
import numpy as np


def get_accuracy(test_labels, pred_lables):
    """
    参数:
    test_labels -- 测试集的真实值
    pred_labels -- 测试集的预测值

    返回:
    accur -- 准确率
    """
    correct = np.sum(test_labels == pred_lables)  # 计算预测正确的数据个数
    n = len(test_labels)  # 总测试集数据个数
    accur = correct/n
    return accur


get_accuracy(y_test, dt_y_predict)

0.7899159663865546

In [6]:
from sklearn.ensemble import BaggingClassifier

tree = DecisionTreeClassifier(criterion='entropy', random_state=28)
bag = BaggingClassifier(tree, n_estimators=100,
                        max_samples=1.0, random_state=3)  # 使用决策树

bag.fit(x_train, y_train)
bt_y_predict = bag.predict(x_test)
bt_y_predict

array([3, 0, 3, 2, 1, 2, 3, 2, 3, 3, 3, 2, 1, 3, 3, 2, 2, 0, 1, 2, 1, 2,
       1, 3, 3, 2, 3, 0, 2, 3, 3, 3, 2, 2, 3, 3, 0, 1, 2, 0, 2, 1, 3, 3,
       1, 3, 2, 3, 3, 3, 3, 3, 1, 2, 2, 0, 1, 3, 2, 3, 3, 2, 0, 2, 2, 3,
       2, 3, 2, 3, 0, 3, 2, 2, 3, 2, 1, 2, 0, 2, 3, 1, 3, 3, 0, 3, 3, 1,
       3, 3, 1, 3, 3, 3, 2, 0, 2, 3, 0, 3, 1, 3, 1, 1, 3, 3, 3, 3, 3, 3,
       3, 1, 1, 1, 3, 0, 3, 3, 3], dtype=int64)

In [7]:
get_accuracy(y_test,bt_y_predict)

0.8991596638655462

In [8]:
from sklearn.ensemble import RandomForestClassifier

# 这里构建 100 棵决策树，采用信息熵来寻找最优划分特征。
rf = RandomForestClassifier(
    n_estimators=100, max_features=None, criterion='entropy')
rf.fit(x_train, y_train)  # 进行模型的训练
rf_y_predict = rf.predict(x_test)
rf_y_predict

array([3, 0, 3, 2, 1, 2, 3, 2, 3, 3, 3, 2, 1, 3, 3, 2, 3, 0, 1, 2, 1, 2,
       1, 3, 3, 2, 3, 0, 2, 3, 3, 3, 2, 2, 3, 3, 0, 1, 2, 0, 2, 1, 3, 3,
       1, 3, 2, 3, 3, 3, 3, 3, 1, 2, 2, 2, 1, 3, 2, 3, 3, 2, 0, 2, 2, 3,
       2, 3, 2, 3, 0, 3, 2, 2, 3, 2, 1, 2, 0, 2, 3, 1, 3, 3, 0, 3, 3, 1,
       3, 3, 1, 3, 3, 3, 2, 0, 2, 3, 0, 3, 1, 3, 1, 1, 3, 3, 3, 3, 3, 3,
       3, 1, 1, 1, 3, 0, 3, 3, 3], dtype=int64)

In [9]:
get_accuracy(y_test, rf_y_predict)

0.8991596638655462

In [10]:
from sklearn.ensemble import AdaBoostClassifier

ad = AdaBoostClassifier(n_estimators=100)
ad.fit(x_train, y_train)
ad_y_predict = ad.predict(x_test)
ad_y_predict

array([3, 3, 3, 2, 0, 3, 3, 2, 3, 3, 3, 2, 1, 3, 3, 2, 2, 0, 1, 2, 1, 3,
       1, 3, 3, 3, 3, 0, 2, 3, 3, 3, 2, 2, 3, 3, 0, 1, 2, 2, 3, 1, 3, 3,
       1, 3, 2, 3, 2, 3, 3, 3, 1, 2, 3, 3, 1, 3, 2, 2, 3, 2, 0, 2, 2, 3,
       2, 3, 3, 3, 0, 3, 2, 2, 3, 2, 1, 2, 0, 2, 2, 1, 3, 3, 3, 3, 3, 1,
       3, 3, 1, 3, 3, 1, 2, 0, 2, 3, 0, 3, 1, 3, 1, 0, 3, 3, 3, 3, 2, 3,
       3, 1, 3, 1, 3, 3, 3, 1, 3], dtype=int64)

In [11]:
get_accuracy(y_test, ad_y_predict)

0.7983193277310925

In [12]:
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(
    n_estimators=100, learning_rate=1.0, random_state=33)
clf.fit(x_train, y_train)
gt_y_predict = clf.predict(x_test)
gt_y_predict

array([3, 0, 3, 2, 1, 3, 3, 2, 3, 3, 3, 2, 1, 3, 3, 2, 2, 0, 1, 2, 1, 2,
       1, 3, 3, 2, 3, 0, 2, 3, 3, 3, 2, 2, 3, 3, 0, 1, 2, 2, 2, 1, 3, 3,
       1, 3, 2, 3, 3, 3, 3, 3, 1, 2, 3, 2, 1, 3, 2, 3, 3, 2, 0, 2, 2, 3,
       2, 3, 2, 3, 0, 3, 2, 2, 3, 2, 1, 2, 0, 2, 2, 1, 3, 3, 0, 3, 3, 1,
       3, 3, 1, 3, 3, 3, 2, 0, 0, 3, 0, 3, 1, 3, 1, 1, 3, 3, 3, 3, 3, 3,
       3, 1, 1, 1, 3, 2, 3, 3, 3], dtype=int64)

In [13]:
get_accuracy(y_test, gt_y_predict)

0.8739495798319328